#Set up build image
FROM node:alpine as builder
WORKDIR /app
COPY .  /app
RUN cd /app && npm set progress=false && npm install
RUN cd /app && npm run build

#Set up webserver image
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/beercounter /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
