FROM microsoft/iis
LABEL Description="IIS with Beer counter"
MAINTAINER Bat-Torstein

RUN powershell Add-WindowsFeature Web-Asp-Net45,Web-Http-Tracing,Web-Scripting-Tools,Web-WebSockets
COPY . c:/inetpub/wwwroot


