FROM microsoft/iis
LABEL Description="IIS with Beer counter"
MAINTAINER Bat-Torstein

#ADD http://go.microsoft.com/fwlink/?LinkID=615137 /build/rewrite_amd64.msi

RUN powershell Add-WindowsFeature Web-Asp-Net45,Web-Http-Tracing,Web-Scripting-Tools,Web-WebSockets

#RUN msiexec /i C:\build\rewrite_amd64.msi /qn /l*v C:\build\urlrewrite.log
COPY . c:/inetpub/wwwroot


