FROM microsoft/iis
LABEL Description="IIS with Beer counter"
LABEL Maintainer = "Bat-Torstein"
RUN powershell Add-WindowsFeature Web-Asp-Net45,Web-Http-Tracing,Web-Scripting-Tools,Web-WebSockets

WORKDIR c:/inetpub/wwwroot
COPY ./dist/beercounter .


